/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2018-02-18 10:57:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1518951416926L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


if(session.getAttribute("savePath")==null){
	String savePath ="C:/Users/penna/Documents/HH 2015-/2017_Kevat/Ohjelmistoprojekti/Oma projekti/Link_Service_siistitty/Link_Service/WebContent/images/uploaded";
	session.setAttribute("savePath", savePath);		
}
if(!request.getRequestURI().equals("/Link_Service/index.jsp")){ 	//jos kutsutaan jotakin muuta kuin index.jsp -sivua
	if(session.getAttribute("SignIn_name")==null){			//ja kirjautumista ei ole tapahtunut
		//response.sendRedirect("index.jsp");
	}
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"http://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/jquery.validate.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/Link_Service/style.css\" type=\"text/css\" >\r\n");
      out.write("<title>BLink</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"header-wrapper\">\r\n");
      out.write("\t\t  <div id=\"header\" class=\"containerheader\">\r\n");
      out.write("\t\t   <div id=\"logo\">\r\n");
      out.write("\t\t\t\t<h1><a href=\"#\">BLink</a></h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"menu\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"signInSuccessful\">\r\n");
      out.write("\t\t\t\t\t\t\tUser: ");
out.print(session.getAttribute("SignIn_name"));
      out.write("<br>\r\n");
      out.write("\t\t\t\t\t\t\t<a style=\"float:right; font-size: 10px; padding: 2px; color:#ababab;\" href=\"Servlet_SignIn?out=1\">Log out</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"menu active\" id=\"boardIcon\" onclick=\"document.location='boards.jsp'\">Boards</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"menu active\" id=\"linkIcon\" onclick=\"document.location='mainview.jsp'\">Links</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t </div>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");

if(session.getAttribute("SignIn_name")==null){		
	out.println("<script>");
	out.println("$('#signInSuccessful').hide();");
	out.println("$('#boardIcon').hide();");
	out.println("$('#linkIcon').hide();");	
	out.println("</script>");	
}

      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("<div id=\"container\">\r\n");

//***ALKU TULEE header.jsp tiedostosta******************************************************************************************************

      out.write("\r\n");
      out.write("<div id=\"kirjautuminen\">\r\n");
      out.write("\t<legend style=\"color: #20e1b6; font-size:14px\">Sign In:</legend>\t\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<form action=\"Servlet_SignIn\" method=\"post\" id=\"SignInForm\">\r\n");
      out.write("\t<label>Email:</label>\t\r\n");
      out.write("\t<input type=\"text\" value=\"test@test.com\" name=\"uid\" id=\"uid\"><br>\r\n");
      out.write("\t<label>Password:</label>\r\n");
      out.write("\t<input type=\"password\" value=\"password\" name=\"pwd\" id=\"pwd\"><br>\r\n");
      out.write("\t<label></label>\r\n");
      out.write("\t<br><br>\r\n");
      out.write("\t<input type=\"button\" class=\"indexbutton\" value=\"Sign In\" id=\"SignInBtn\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<input type=\"button\" class=\"indexbutton\" value=\"New User\" id=\"RegisterBtn\" onclick=\"document.location='newUser.jsp'\"><br>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

if(request.getAttribute("message")!=null){	
	response.sendRedirect("Servlet_GetPhotos?link_id=" + request.getParameter("link_id"));
	Thread.sleep(5000);//odotetaan 5 sekuntia, jotta photo ehtii latautua
}

      out.write('\r');
      out.write('\n');

	if(request.getParameter("singin")!=null){
		if(request.getParameter("signin").equals("0")){
			out.print("Adding the customer was not succesful!");	
		} if(request.getParameter("signin").equals("1")){
			out.print("New User have been added!");	
		}if(request.getParameter("signin").equals("2")){
			out.print("Incorrect user details, please try again!");	
		} 
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t$(\"#kirjautuminen\").css({\r\n");
      out.write("\t\t\t\"width\": \"300px\", \r\n");
      out.write("\t\t\t\"border-radius\": \"15px\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#SignInBtn\").click(function(){\t\t\r\n");
      out.write("\t\t\tif($(\"#uid\").val().length>0&&$(\"#pwd\").val().length>0){\r\n");
      out.write("\t\t\t\tdocument.forms[\"SignInForm\"].submit();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
